apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-studies-app
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s
    repoURL: 'https://github.com/pedrofurtado/argocd-studies'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
