version: '3'

services:
  app:
    restart: always
    volumes:
      - ./:/app
    command: /bin/bash -c 'go run main.go'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3006:8080
